// generated by jsonenums -type=Status; DO NOT EDIT

package status

import (
	"encoding/json"
	"fmt"
)

var (
	_StatusNameToValue = map[string]Status{
		"Draft":         Draft,
		"PendingReview": PendingReview,
		"Published":     Published,
	}

	_StatusValueToName = map[Status]string{
		Draft:         "Draft",
		PendingReview: "PendingReview",
		Published:     "Published",
	}
)

func init() {
	var v Status
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		_StatusNameToValue = map[string]Status{
			interface{}(Draft).(fmt.Stringer).String():         Draft,
			interface{}(PendingReview).(fmt.Stringer).String(): PendingReview,
			interface{}(Published).(fmt.Stringer).String():     Published,
		}
	}
}

// MarshalJSON is generated so Status satisfies json.Marshaler.
func (r Status) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := _StatusValueToName[r]
	if !ok {
		return nil, fmt.Errorf("invalid Status: %d", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so Status satisfies json.Unmarshaler.
func (r *Status) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Status should be a string, got %s", data)
	}
	v, ok := _StatusNameToValue[s]
	if !ok {
		return fmt.Errorf("invalid Status %q", s)
	}
	*r = v
	return nil
}
