// Code generated by "stringer -type=Capability capability.go"; DO NOT EDIT

package capabilities

import "fmt"

const _Capability_name = "CreateUserCreatePageCreateArticleCreateCategoryCreateTaxonomyUploadPictureInstallThemeReadUserReadPageReadArticleReadCategoryReadTaxonomyReadPictureReadThemeUpdateUserUpdatePageUpdateArticleUpdateCategoryUpdateTaxonomyUpdatePictureSwitchThemeDeleteUserDeletePageDeleteArticleDeleteCategoryDeleteTaxonomyDeletePictureDeleteThemeManageConfigs"

var _Capability_index = [...]uint16{0, 10, 20, 33, 47, 61, 74, 86, 94, 102, 113, 125, 137, 148, 157, 167, 177, 190, 204, 218, 231, 242, 252, 262, 275, 289, 303, 316, 327, 340}

func (i Capability) String() string {
	i -= 1
	if i >= Capability(len(_Capability_index)-1) {
		return fmt.Sprintf("Capability(%d)", i+1)
	}
	return _Capability_name[_Capability_index[i]:_Capability_index[i+1]]
}
