// Code generated by "stringer -type=Visibility"; DO NOT EDIT

package visibility

import "fmt"

const _Visibility_name = "PublicPrivate"

var _Visibility_index = [...]uint8{0, 6, 13}

func (i Visibility) String() string {
	if i >= Visibility(len(_Visibility_index)-1) {
		return fmt.Sprintf("Visibility(%d)", i)
	}
	return _Visibility_name[_Visibility_index[i]:_Visibility_index[i+1]]
}
